// Generated by gencpp from file shared_files/drive.msg
// DO NOT EDIT!


#ifndef SHARED_FILES_MESSAGE_DRIVE_H
#define SHARED_FILES_MESSAGE_DRIVE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace shared_files
{
template <class ContainerAllocator>
struct drive_
{
  typedef drive_<ContainerAllocator> Type;

  drive_()
    : direction(0)
    , speed(0)  {
    }
  drive_(const ContainerAllocator& _alloc)
    : direction(0)
    , speed(0)  {
  (void)_alloc;
    }



   typedef uint32_t _direction_type;
  _direction_type direction;

   typedef uint32_t _speed_type;
  _speed_type speed;




  typedef boost::shared_ptr< ::shared_files::drive_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::shared_files::drive_<ContainerAllocator> const> ConstPtr;

}; // struct drive_

typedef ::shared_files::drive_<std::allocator<void> > drive;

typedef boost::shared_ptr< ::shared_files::drive > drivePtr;
typedef boost::shared_ptr< ::shared_files::drive const> driveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::shared_files::drive_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::shared_files::drive_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace shared_files

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'shared_files': ['/home/dguerra/Aggregator/prototype/src/shared_files/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::shared_files::drive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::shared_files::drive_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::shared_files::drive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::shared_files::drive_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shared_files::drive_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shared_files::drive_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::shared_files::drive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89726c303325757051a3ce7b2bc535e7";
  }

  static const char* value(const ::shared_files::drive_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89726c3033257570ULL;
  static const uint64_t static_value2 = 0x51a3ce7b2bc535e7ULL;
};

template<class ContainerAllocator>
struct DataType< ::shared_files::drive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "shared_files/drive";
  }

  static const char* value(const ::shared_files::drive_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::shared_files::drive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 direction\n\
uint32 speed\n\
";
  }

  static const char* value(const ::shared_files::drive_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::shared_files::drive_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direction);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct drive_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::shared_files::drive_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::shared_files::drive_<ContainerAllocator>& v)
  {
    s << indent << "direction: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.direction);
    s << indent << "speed: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SHARED_FILES_MESSAGE_DRIVE_H
